/** @format */
import { Prisma } from "@/prisma/generated/client";

/**
 * Represents the global configuration settings for the application.
 *
 * This type is generated by Prisma and corresponds to the `Config` model
 * in your database. It includes fields for:
 *
 * - Basic information: `id`, `name`, `logo`, `themeColors`
 * - SMTP/email configuration: `smtpHost`, `smtpPort`, `smtpUser`, `smtpPassword`, `emailFrom`
 * - Registration rules: `allowPublicRegistration`, `studentEmailDomain`, `staffEmailDomain`
 * - Metadata: `updatedAt` (automatically updated timestamp)
 */
export type { Config } from "@/prisma/generated/client";

/**
 * Input type for creating a Config record.
 */
export type ConfigCreateType = Prisma.ConfigCreateInput;

/**
 * Input type for updating a Config record.
 */
export type ConfigUpdateType = Prisma.ConfigUpdateInput;
