/** @format */
import {Prisma} from "@/prisma/generated/client";

/**
 * Represents the global configuration settings for the application.
 *
 * This type is generated by Prisma and corresponds to the `Config` model
 * in your database. It includes fields for:
 *
 * - Basic information: `id`, `name`, `logo`, `themeColors`
 * - SMTP/email configuration: `smtpHost`, `smtpPort`, `smtpUser`, `smtpPassword`, `emailFrom`
 * - Registration rules: `allowPublicRegistration`, `studentEmailDomain`, `staffEmailDomain`
 * - Metadata: `updatedAt` (automatically updated timestamp)
 */
export type {Config} from "@/prisma/generated/client";

/**
 * Theme color type for one mode (light or dark)
 */
export type ThemeModeColors = {
    primary: string;
    primaryHover: string;
    primaryLight: string;
    primaryDark: string;
    primaryForeground: string;

    secondary: string;
    secondaryHover: string;
    secondaryLight: string;
    secondaryDark: string;
    secondaryForeground: string;

    accent: string;
    accentHover: string;
    accentLight: string;
    accentDark: string;
    accentForeground: string;

    success: string;
    successLight: string;
    successForeground: string;

    error: string;
    errorLight: string;
    errorForeground: string;

    warning: string;
    warningLight: string;
    warningForeground: string;

    info: string;
    infoLight: string;
    infoForeground: string;

    background: string;
    foreground: string;
    surface: string;
    surfaceElevated: string;

    textPrimary: string;
    textSecondary: string;
    textTertiary: string;
    textDisabled: string;

    border: string;
    input: string;
    ring: string;

    muted: string;
    mutedForeground: string;
};

/**
 * Full theme colors type (light + dark)
 */
export type ThemeColors = {
    light: ThemeModeColors;
    dark: ThemeModeColors;
};

/**
 * Input type for creating a Config record.
 *
 * Extends the Prisma create type, but enforces `themeColors` to match `ThemeColors`.
 */
export type ConfigCreateType = Omit<Prisma.ConfigCreateInput, "themeColors"> & {
    themeColors: ThemeColors;
};

/**
 * Input type for updating a Config record.
 *
 * Extends the Prisma update type, but enforces `themeColors` to match `ThemeColors`.
 */
export type ConfigUpdateType = Omit<Prisma.ConfigUpdateInput, "themeColors"> & {
    themeColors?: ThemeColors;
};

/**
 * Default theme colors for light and dark mode
 */
export const defaultThemeColors: ThemeColors = {
    light: {
        primary: "#14b8a6",
        primaryHover: "#0d9488",
        primaryLight: "#5eead4",
        primaryDark: "#0f766e",
        primaryForeground: "#ffffff",

        secondary: "#64748b",
        secondaryHover: "#475569",
        secondaryLight: "#94a3b8",
        secondaryDark: "#334155",
        secondaryForeground: "#ffffff",

        accent: "#f59e0b",
        accentHover: "#d97706",
        accentLight: "#fbbf24",
        accentDark: "#b45309",
        accentForeground: "#ffffff",

        success: "#10b981",
        successLight: "#d1fae5",
        successForeground: "#ffffff",

        error: "#ef4444",
        errorLight: "#fee2e2",
        errorForeground: "#ffffff",

        warning: "#f59e0b",
        warningLight: "#fef3c7",
        warningForeground: "#ffffff",

        info: "#3b82f6",
        infoLight: "#dbeafe",
        infoForeground: "#ffffff",

        background: "#ffffff",
        foreground: "#171717",
        surface: "#f9fafb",
        surfaceElevated: "#ffffff",

        textPrimary: "#0f172a",
        textSecondary: "#64748b",
        textTertiary: "#94a3b8",
        textDisabled: "#cbd5e1",

        border: "#e2e8f0",
        input: "#e2e8f0",
        ring: "#14b8a6",

        muted: "#f1f5f9",
        mutedForeground: "#64748b",
    },

    dark: {
        primary: "#5eead4",
        primaryHover: "#2dd4bf",
        primaryLight: "#99f6e4",
        primaryDark: "#14b8a6",
        primaryForeground: "#0a0a0a",

        secondary: "#94a3b8",
        secondaryHover: "#cbd5e1",
        secondaryLight: "#cbd5e1",
        secondaryDark: "#64748b",
        secondaryForeground: "#0a0a0a",

        accent: "#fbbf24",
        accentHover: "#fcd34d",
        accentLight: "#fde68a",
        accentDark: "#f59e0b",
        accentForeground: "#0a0a0a",

        success: "#34d399",
        successLight: "#064e3b",
        successForeground: "#0a0a0a",

        error: "#f87171",
        errorLight: "#7f1d1d",
        errorForeground: "#ffffff",

        warning: "#fbbf24",
        warningLight: "#78350f",
        warningForeground: "#0a0a0a",

        info: "#60a5fa",
        infoLight: "#1e3a8a",
        infoForeground: "#0a0a0a",

        background: "#0a0a0a",
        foreground: "#f1f5f9",
        surface: "#0a0a0a",
        surfaceElevated: "#141414",

        textPrimary: "#f1f5f9",
        textSecondary: "#cbd5e1",
        textTertiary: "#94a3b8",
        textDisabled: "#64748b",

        border: "#2a2a2a",
        input: "#1f1f1f",
        ring: "#5eead4",

        muted: "#1a1a1a",
        mutedForeground: "#a1a1aa",
    },
};

/**
 * Default global configuration for the platform.
 */
export const defaultConfig: ConfigCreateType = {
    name: "",
    logo: "",
    themeColors: defaultThemeColors,

    smtpHost: "",
    smtpPort: 587,
    smtpUser: "",
    smtpPassword: "",
    emailFrom: "",

    allowPublicRegistration: false,
    studentEmailDomain: null,
    staffEmailDomain: null,
};
